-- 코드를 입력하세요
SELECT DISTINCT CP.CART_ID
FROM CART_PRODUCTS CP
INNER JOIN (
    SELECT TMP.CART_ID, TMP.NAME
    FROM CART_PRODUCTS TMP
    WHERE NAME = 'Milk'
) CP2
ON CP.CART_ID = CP2.CART_ID
WHERE CP.NAME = 'Yogurt'
ORDER BY CP.CART_ID
