SELECT ROUND(AVG(TMP.TMPCNT), 2) AS AVERAGE_DAILY_PERCENT
FROM (
    SELECT ACTION_DATE, COUNT(DISTINCT T2.POST_ID) / COUNT(DISTINCT T1.POST_ID) * 100 TMPCNT
    FROM ACTIONS T1
    LEFT JOIN REMOVALS T2
     ON T1.POST_ID = T2.POST_ID
    WHERE T1.ACTION = 'REPORT' AND T1.EXTRA = 'SPAM'
    GROUP BY T1.ACTION_DATE
) TMP
