-- 코드를 입력하세요
SELECT TEMP.ANIMAL_ID, TEMP.NAME
FROM (
    SELECT AO.ANIMAL_ID, AO.NAME
    FROM ANIMAL_INS AI
    JOIN ANIMAL_OUTS AO
    ON AI.ANIMAL_ID = AO.ANIMAL_ID
    ORDER BY AO.DATETIME - AI.DATETIME DESC
) TEMP
WHERE ROWNUM <= 2

