-- 코드를 입력하세요
SELECT CRCC.CAR_ID, CRCC.CAR_TYPE, FLOOR(CRCC.DAILY_FEE * 30 * (1 - CRCDP.DISCOUNT_RATE / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CRCC
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE
WHERE CRCC.CAR_TYPE IN ('세단', 'SUV')
AND CRCC.CAR_ID NOT IN (SELECT CAR_ID
                         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                         WHERE END_DATE >= '2022-11-1' 
                               AND START_DATE <= '2022-11-30')
AND CRCDP.DURATION_TYPE = '30일 이상'
    
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY 3 DESC, 2, 1 DESC;
