-- 코드를 입력하세요SELECT T1.CAR_ID, (T1.DAILY_FEE - (T1.DAILY_FEE / 100 * T3.DISCOUNT_RATE)) * 30 FEE
SELECT CAR_ID, CAR_TYPE, FEE
FROM (
    SELECT DISTINCT TMP.CAR_ID, TMP.CAR_TYPE, TMP.DISCOUNT_RATE, TMP.DAILY_FEE,
    (TMP.DAILY_FEE - (TMP.DAILY_FEE / 100 * TMP.DISCOUNT_RATE)) * 30 FEE
    FROM (
        SELECT T1.CAR_ID, T1.CAR_TYPE, T3.DISCOUNT_RATE, T1.DAILY_FEE
        FROM CAR_RENTAL_COMPANY_CAR T1
        JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY T2
        ON T1.CAR_ID = T2.CAR_ID
        JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN T3
        ON T1.CAR_TYPE = T3.CAR_TYPE AND T3.DURATION_TYPE = '30일 이상'
        WHERE T1.CAR_TYPE IN ('SUV', '세단')
        AND T1.CAR_ID NOT IN (
                            SELECT DISTINCT CAR_ID
                            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                            WHERE START_DATE <= TO_DATE('2022-11-30', 'YYYY-MM-DD')
                            AND END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD')
        )
    ) TMP
) TMP2
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;
