-- 코드를 입력하세요
SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO RI
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAXFAVOR
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) TMP
ON RI.FOOD_TYPE = TMP.FOOD_TYPE AND RI.FAVORITES = TMP.MAXFAVOR
ORDER BY FOOD_TYPE DESC

