-- 코드를 입력하세요
SELECT UGU.USER_ID, UGU.NICKNAME, UGU.CITY||' ' ||UGU.STREET_ADDRESS1||' ' ||UGU.STREET_ADDRESS2 전체주소, 
REGEXP_REPLACE(UGU.TLNO, '(.{3})(.+)(.{4})', '\1-\2-\3') 전화번호
FROM USED_GOODS_USER UGU
JOIN (
    SELECT WRITER_ID, COUNT(BOARD_ID)
    FROM USED_GOODS_BOARD UGB
    GROUP BY WRITER_ID
    HAVING COUNT(BOARD_ID) >= 3
) TMP
ON UGU.USER_ID = TMP.WRITER_ID
ORDER BY 1 DESC