-- 코드를 입력하세요
SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, TMP.SCORE AS SCORE
FROM REST_INFO RI
JOIN (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
) TMP
ON RI.REST_ID = TMP.REST_ID
WHERE SUBSTR(RI.ADDRESS, 1, 2) = '서울'
ORDER BY SCORE DESC, FAVORITES DESC;
