SELECT TO_CHAR(SALES_DATE, 'YYYY') YEAR, TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) MONTH, UI.GENDER, COUNT(DISTINCT UI.USER_ID) USERS
FROM USER_INFO UI
JOIN ONLINE_SALE OS
ON OS.USER_ID = UI.USER_ID
GROUP BY TO_CHAR(SALES_DATE, 'YYYY'), TO_CHAR(SALES_DATE, 'MM'), UI.GENDER
HAVING UI.GENDER IS NOT NULL
ORDER BY 1, 2, 3
