# Write your MySQL query statement below
SELECT SUM(T1.APPLE_COUNT + COALESCE(T2.APPLE_COUNT, 0)) AS APPLE_COUNT, SUM(T1.ORANGE_COUNT + COALESCE(T2.ORANGE_COUNT, 0)) AS ORANGE_COUNT
FROM BOXES T1
LEFT JOIN CHESTS T2
ON T1.CHEST_ID = T2.CHEST_ID