-- SELECT EXTRACT(YEAR FROM JOINED) YEAR, COUNT(USER_ID)
-- FROM USER_INFO
-- GROUP BY EXTRACT(YEAR FROM JOINED)
-- HAVING EXTRACT(YEAR FROM JOINED) = '2021'

SELECT EXTRACT(YEAR FROM OS.SALES_DATE) YEAR, EXTRACT(MONTH FROM OS.SALES_DATE) MONTH, COUNT(DISTINCT TMP.USER_ID) PURCHASED_USERS, ROUND((COUNT(DISTINCT OS.USER_ID) / 
   (SELECT COUNT(USER_ID)
    FROM USER_INFO
    GROUP BY EXTRACT(YEAR FROM JOINED)
    HAVING EXTRACT(YEAR FROM JOINED) = '2021')), 1) PUCHASED_RATIO
FROM ONLINE_SALE OS
JOIN (
    SELECT USER_ID
    FROM USER_INFO
    WHERE EXTRACT(YEAR FROM JOINED) = '2021'
) TMP
ON OS.USER_ID = TMP.USER_ID
GROUP BY EXTRACT(YEAR FROM OS.SALES_DATE), EXTRACT(MONTH FROM OS.SALES_DATE)
ORDER BY 1, 2;

