-- 코드를 입력하세요
-- SELECT CAR_ID,
-- CASE WHEN TO_CHAR(START_DATE, 'YYYYMMDD') <= '20221016' AND TO_CHAR(END_DATE, 'YYYYMMDD') >= '20221016' THEN '대여중'
-- ELSE '대여 가능'
-- END AVAILABILITY
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- GROUP BY CAR_ID

-- SELECT CAR_ID,
-- CASE WHEN TO_CHAR(START_DATE, 'YYYYMMDD') <= '20221016' AND TO_CHAR(END_DATE, 'YYYYMMDD') >= '20221016' THEN '대여중'
-- ELSE '대여 가능'
-- END AVAILABILITY
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- -- WHERE TO_CHAR(START_DATE, 'YYYYMMDD') <= '20221016' AND TO_CHAR(END_DATE, 'YYYYMMDD') >= '20221016'

SELECT DISTINCT T1.CAR_ID, NVL(T3.AVAILABILITY, '대여 가능') AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY T1
LEFT JOIN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        GROUP BY CAR_ID
    ) T2
    ON T1.CAR_ID = T2.CAR_ID
LEFT JOIN (
        SELECT CAR_ID, '대여중' AVAILABILITY
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE TO_CHAR(START_DATE, 'YYYYMMDD') <= '20221016' AND TO_CHAR(END_DATE, 'YYYYMMDD') >= '20221016'
        GROUP BY CAR_ID
) T3
ON T1.CAR_ID = T3.CAR_ID
ORDER BY 1 DESC
-- SELECT CAR_ID, '대여중' AVAILABILITY
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- WHERE TO_CHAR(START_DATE, 'YYYYMMDD') <= '20221016' AND TO_CHAR(END_DATE, 'YYYYMMDD') >= '20221016'
-- GROUP BY CAR_ID