SELECT "1Q" QUARTER, COUNT(ID) ECOLI_COUNT 
FROM ECOLI_DATA
WHERE MONTH(DIFFERENTIATION_DATE) >= 1 && MONTH(DIFFERENTIATION_DATE) <= 3
UNION
SELECT "2Q" QUARTER, COUNT(ID) ECOLI_COUNT 
FROM ECOLI_DATA
WHERE MONTH(DIFFERENTIATION_DATE) >= 4 && MONTH(DIFFERENTIATION_DATE) <= 6

UNION
SELECT "3Q" QUARTER, COUNT(ID) ECOLI_COUNT 
FROM ECOLI_DATA
WHERE MONTH(DIFFERENTIATION_DATE) >= 7 && MONTH(DIFFERENTIATION_DATE) <= 9

UNION
SELECT "4Q" QUARTER, COUNT(ID) ECOLI_COUNT 
FROM ECOLI_DATA
WHERE MONTH(DIFFERENTIATION_DATE) >= 10 && MONTH(DIFFERENTIATION_DATE) <= 12
ORDER BY QUARTER