WITH MAXTABLE AS (
    SELECT COMPANY_ID, MAX(SALARY) MAX
    FROM SALARIES
    GROUP BY COMPANY_ID
)

SELECT T1.COMPANY_ID, T1.EMPLOYEE_ID, T1.EMPLOYEE_NAME, ROUND(T1.SALARY - (T1.SALARY * (T2.RATE / 100))) SALARY
FROM SALARIES T1
JOIN (
    SELECT COMPANY_ID, MAX, CASE WHEN MAX > 10000 THEN 49
    WHEN MAX >= 1000 AND MAX <= 10000 THEN 24
    ELSE 0 END AS RATE
    FROM MAXTABLE
    ) T2
 ON T1.COMPANY_ID = T2.COMPANY_ID