SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, (FP.PRICE * TMP.CNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FP
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS CNT
    FROM FOOD_ORDER
    WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') = '2022-05'    
    GROUP BY PRODUCT_ID
) TMP
ON FP.PRODUCT_ID = TMP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID

