-- 코드를 입력하세요
SELECT PR.PRODUCT_CODE, SUM(OS.SALES_AMOUNT)*PRICE AS SALES
FROM PRODUCT PR, OFFLINE_SALE OS
WHERE PR.PRODUCT_ID LIKE OS.PRODUCT_ID
GROUP BY PR.PRODUCT_CODE
ORDER BY SALES DESC, PR.PRODUCT_CODE;