SELECT TMP.HISTORY_ID, FLOOR(TMP.DAILY_FEE * (1 - COALESCE(T3.DISCOUNT_RATE, 0) / 100) * DURATION) AS FEE
FROM (
        SELECT T1.CAR_ID, T1.CAR_TYPE, T2.HISTORY_ID, T1.DAILY_FEE, T2.START_DATE, T2.END_DATE, T2.END_DATE - T2.START_DATE + 1 DURATION
        FROM CAR_RENTAL_COMPANY_CAR T1
        JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY T2
            ON T1.CAR_ID = T2.CAR_ID
        WHERE T1.CAR_TYPE = '트럭'
) TMP
JOIN CAR_RENTAL_COMPANY_CAR C ON TMP.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN T3
ON TMP.CAR_TYPE = T3.CAR_TYPE
AND ((TMP.DURATION >= 7 AND TMP.DURATION < 30 AND T3.DURATION_TYPE = '7일 이상')
OR (TMP.DURATION >= 30 AND TMP.DURATION < 90 AND T3.DURATION_TYPE = '30일 이상')
OR (TMP.DURATION >= 90 AND T3.DURATION_TYPE = '90일 이상'))
ORDER BY 2 DESC, 1 DESC
