SELECT H.HOUR AS HOUR, NVL(C.COUNT, 0)
FROM (
    SELECT LEVEL - 1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
) H
LEFT JOIN (
    SELECT EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) AS HOUR, COUNT(ANIMAL_ID) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP))
) C
ON H.HOUR = C.HOUR
ORDER BY HOUR 

    


