SELECT UGU.USER_ID, UGU.NICKNAME, TMP.PRICESUM TOTAL_SALES
FROM USED_GOODS_USER UGU
JOIN (
    SELECT WRITER_ID, SUM(PRICE) PRICESUM
    FROM USED_GOODS_BOARD 
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000 
) TMP
ON UGU.USER_ID = TMP.WRITER_ID
ORDER BY 3;
