SELECT HE.EMP_NO, HE.EMP_NAME, 
    CASE
    WHEN AVGSCORE >= 96 THEN 'S'
    WHEN AVGSCORE >= 90 THEN 'A'
    WHEN AVGSCORE >= 80 THEN 'B'
    ELSE 'C' END GRADE,
    CASE
    WHEN AVGSCORE >= 96 THEN SAL * 0.2
    WHEN AVGSCORE >= 90 THEN SAL * 0.15
    WHEN AVGSCORE >= 80 THEN SAL * 0.1
    ELSE 0 END BONUS
FROM HR_EMPLOYEES HE
JOIN (
    SELECT EMP_NO, AVG(SCORE) AVGSCORE
    FROM HR_GRADE
    GROUP BY EMP_NO, YEAR
) HG
    ON HE.EMP_NO = HG.EMP_NO
ORDER BY 1;
