SELECT T1.BUSINESS_ID
FROM EVENTS T1
JOIN (
    SELECT EVENT_TYPE, AVG(OCCURRENCES) AVG
    FROM EVENTS
    GROUP BY EVENT_TYPE
    ) T2
 ON T1.EVENT_TYPE =T2.EVENT_TYPE
WHERE T1.OCCURRENCES > T2.AVG
GROUP BY BUSINESS_ID
HAVING COUNT(BUSINESS_ID) >= 2