-- -- 코드를 입력하세요
SELECT EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS A
GROUP BY EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP))
HAVING EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) >= 9 AND EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) <= 20
ORDER BY HOUR

