-- -- 코드를 입력하세요
-- SELECT MP.MEMBER_NAME
-- FROM MEMBER_PROFILE MP
-- JOIN (
--     SELECT MEMBER_ID, MAX, CNT 
--     FROM (
--         SELECT MEMBER_ID, MAX(MEMBER_ID) MAX, COUNT(MEMBER_ID) CNT
--         FROM REST_REVIEW
--         GROUP BY MEMBER_ID
--         ORDER BY CNT DESC
--     ) TMP
--     WHERE ROWNUM <= 1
-- ) TMP
-- ON MP.MEMBER_ID = TMP.MEMBER_ID

SELECT MP.MEMBER_NAME, REVIEW_TEXT, TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
FROM MEMBER_PROFILE MP
JOIN (
    SELECT RR.MEMBER_ID, RR.REVIEW_TEXT, RR.REVIEW_DATE
    FROM REST_REVIEW RR
    WHERE (
            SELECT MEMBER_ID
            FROM (
                SELECT MEMBER_ID, MAX(MEMBER_ID) MAX, COUNT(MEMBER_ID) CNT
                FROM REST_REVIEW
                GROUP BY MEMBER_ID
                ORDER BY CNT DESC
            ) TMP
            WHERE ROWNUM <= 1
    ) = RR.MEMBER_ID
) TMP
ON MP.MEMBER_ID = TMP.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT

