SELECT EXTRACT(MONTH FROM CRCRH.START_DATE) MONTH, TMP.CAR_ID, COUNT(TMP.CAR_ID) RECORDS
FROM (
SELECT CAR_ID, COUNT(CAR_ID) CNT
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_CHAR(START_DATE, 'YYYYMM') >= '202208'
AND TO_CHAR(START_DATE, 'YYYYMM') <= '202210'
GROUP BY CAR_ID
HAVING COUNT(CAR_ID) >= 5
) TMP
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
ON CRCRH.CAR_ID = TMP.CAR_ID
WHERE TO_CHAR(START_DATE, 'YYYYMM') >= '202208'
AND TO_CHAR(START_DATE, 'YYYYMM') <= '202210'
GROUP BY EXTRACT(MONTH FROM CRCRH.START_DATE), TMP.CAR_ID
ORDER BY 1, 2 DESC