SELECT TMP.YEAR,
        MAXYEAR - ED.SIZE_OF_COLONY AS YEAR_DEV,
        ID
FROM ECOLI_DATA ED,
(SELECT YEAR(DIFFERENTIATION_DATE) YEAR,
        MAX(SIZE_OF_COLONY) MAXYEAR
 FROM ECOLI_DATA ED2
 GROUP BY YEAR
) TMP
WHERE TMP.YEAR = YEAR(ED.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV
