
SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM (
    SELECT MAX(LENGTH) AS MX, FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) TMP
JOIN FISH_INFO FI
ON FI.LENGTH = TMP.MX AND FI.FISH_TYPE = TMP.FISH_TYPE
JOIN FISH_NAME_INFO FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE
ORDER BY FI.ID;
