SELECT FI.ID, FNI.FISH_NAME, T1.LENGTH
FROM (
SELECT FISH_TYPE, MAX(LENGTH) LENGTH
FROM FISH_INFO
GROUP BY FISH_TYPE
    ) T1
JOIN FISH_INFO FI
ON T1.FISH_TYPE = FI.FISH_TYPE AND T1.LENGTH = FI.LENGTH
JOIN FISH_NAME_INFO FNI
ON T1.FISH_TYPE = FNI.FISH_TYPE
ORDER BY 1;