SELECT T1.SCORE, T1.EMP_NO, T2.EMP_NAME, T2.POSITION, T2.EMAIL
FROM
    (
    SELECT EMP_NO, SUM(SCORE) SCORE
    FROM HR_GRADE
    WHERE YEAR = '2022'
    GROUP BY EMP_NO
    ORDER BY 2 DESC
    LIMIT 1
    ) T1
JOIN HR_EMPLOYEES T2
    ON T1.EMP_NO = T2.EMP_NO