-- 코드를 입력하세요
# SELECT AO.ANIMAL_ID, AO.NAME
# FROM ANIMAL_OUTS AO, ANIMAL_INS AI
# OUTER JOIN ANIMAL_INS AI
# ON AO.ANIMAL_ID = AI.ANIMAL_ID
# WHERE AO.DATETIME < AI.DATETIME
# ORDER BY AI.DATETIME;

SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AO, ANIMAL_INS AI
WHERE AO.ANIMAL_ID = AI.ANIMAL_ID AND AO.DATETIME < AI.DATETIME
ORDER BY AI.DATETIME;
