-- 코드를 입력하세요
SELECT FP.CATEGORY, FP.PRICE AS MAX_PRICE, FP.PRODUCT_NAME
FROM (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING CATEGORY IN ('식용유', '과자', '국', '김치')
) TMP
JOIN FOOD_PRODUCT FP
ON TMP.MAX_PRICE = FP.PRICE AND TMP.CATEGORY = FP.CATEGORY
ORDER BY MAX_PRICE DESC
