SELECT COUNT(T3.ID) FISH_COUNT, MAX(T3.LENGTH) MAX_LENGTH, T3.FISH_TYPE
FROM (
    SELECT T1.FISH_TYPE
    FROM (
        SELECT FISH_TYPE, AVG(LENGTH) AVERAGE
        FROM FISH_INFO
        GROUP BY FISH_TYPE
        ) T1
    WHERE T1.AVERAGE >= 33
    ) T2
JOIN FISH_INFO T3
ON T2.FISH_TYPE = T3.FISH_TYPE
GROUP BY T3.FISH_TYPE
ORDER BY 3;