SELECT COUNT(FI.ID) AS FISH_COUNT, MAX(FI.LENGTH) AS MAX_LENGTH, TMP.FISH_TYPE
FROM (
    SELECT FISH_TYPE, AVG(IF(LENGTH IS NULL OR LENGTH <= 10, 10, LENGTH)) AVG_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) TMP
JOIN FISH_INFO FI USING(FISH_TYPE)
WHERE TMP.AVG_LENGTH >= 33
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE