SELECT CASE
    WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'FRONT END') AND 
         SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME = 'Python') THEN 'A'
    WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'
    WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'FRONT END') THEN 'C'
    ELSE NULL
    END GRADE
    , ID, EMAIL
FROM DEVELOPERS
GROUP BY GRADE, ID ,EMAIL
HAVING GRADE IS NOT NULL
ORDER BY 1, 2;
